// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/3/2024, 1:29:25 PM
const configMerger = require("/Users/michelnassar/Desktop/Projects/NuxtJs/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/michelnassar/Desktop/Projects/NuxtJs/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/michelnassar/Desktop/Projects/NuxtJs/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/michelnassar/Desktop/Projects/NuxtJs/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/michelnassar/Desktop/Projects/NuxtJs/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/michelnassar/Desktop/Projects/NuxtJs/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/michelnassar/Desktop/Projects/NuxtJs/plugins/**/*.{js,ts,mjs}","/Users/michelnassar/Desktop/Projects/NuxtJs/composables/**/*.{js,ts,mjs}","/Users/michelnassar/Desktop/Projects/NuxtJs/utils/**/*.{js,ts,mjs}","/Users/michelnassar/Desktop/Projects/NuxtJs/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/michelnassar/Desktop/Projects/NuxtJs/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/michelnassar/Desktop/Projects/NuxtJs/app.config.{js,ts,mjs}"] }));

module.exports = config
